/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cat.proven.guiprod.view;

import cat.proven.guiprod.model.Model;
import cat.proven.guiprod.model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author dax
 */
public class MainFrame extends javax.swing.JFrame {
    private Model model;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        productForm1.setModel(model);
        displayHomePanel();
    }
    
    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new cat.proven.guiprod.view.home();
        productForm1 = new cat.proven.guiprod.view.ProductFormPanel();
        MenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        itemProduct = new javax.swing.JMenuItem();
        itemProductList = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Product manager");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        homePanel.setInheritsPopupMenu(true);
        homePanel.setName(""); // NOI18N
        getContentPane().add(homePanel, java.awt.BorderLayout.CENTER);
        getContentPane().add(productForm1, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handlerMenu(evt);
            }
        });

        home.setText("Home");
        home.setActionCommand("home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handlerMenu(evt);
            }
        });
        fileMenu.add(home);

        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        fileMenu.add(exit);

        MenuBar.add(fileMenu);

        editMenu.setText("Edit");

        itemProduct.setText("Product Form");
        itemProduct.setActionCommand("ProductForm");
        itemProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handlerMenu(evt);
            }
        });
        editMenu.add(itemProduct);

        itemProductList.setText("Product List");
        itemProductList.setActionCommand("ProductList");
        editMenu.add(itemProductList);

        MenuBar.add(editMenu);

        menuHelp.setText("Help");
        MenuBar.add(menuHelp);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int answer = JOptionPane.showConfirmDialog(this, "Sure?", "Exit application", JOptionPane.OK_CANCEL_OPTION);
        if (answer == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int answer = JOptionPane.showConfirmDialog(this, "Sure?", "Exit application", JOptionPane.OK_CANCEL_OPTION);
        if (answer == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void handlerMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handlerMenu
        String action = evt.getActionCommand();
        
        if (action != null){
            switch(action){
                case "home":
                    displayHomePanel();
                    break;
                case "ProductForm":
                    displayProductForm();
                    break;
                case "ProductList":
                    displayProductList();
                    break;
                
            }
        }
    }//GEN-LAST:event_handlerMenu

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Model model = new Model();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame frame = new MainFrame();
                frame.setModel(model);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem home;
    private cat.proven.guiprod.view.home homePanel;
    private javax.swing.JMenuItem itemProduct;
    private javax.swing.JMenuItem itemProductList;
    private javax.swing.JMenu menuHelp;
    private cat.proven.guiprod.view.ProductFormPanel productForm1;
    // End of variables declaration//GEN-END:variables

    private void displayHomePanel() {
        setContentPane(homePanel);
        validate();
    }

    private void displayProductForm() {
        setContentPane(productForm1);
        validate();
    }
    
    private void displayProductList() {
        ProductListPanel panel = new ProductListPanel(model);
        setContentPane(panel);
        validate();
    }
    
//    public void clearForm() {
//        productToForm(new Product(0, "", "", 0.0, 0));
//    }
//    
//    private void productToForm(Product product) {
//        tfId.setText(String.valueOf(product.getId()));
//        tfCode.setText(product.getCode());
//        tfDescription.setText(product.getDescription());
//        tfPrice.setText(String.valueOf(product.getPrice()));
//        tfStock.setText(String.valueOf(product.getStock()));
//    }
}
