/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cat.proven.guiprod.view;

import cat.proven.guiprod.model.Model;
import cat.proven.guiprod.model.Product;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author dax
 */
public class ProductFormPanel extends javax.swing.JPanel {

    private Model model;
    private Product product;
    //
    private final ActionListener actionListener;

    /**
     * Creates new form ProductForm
     */
    public ProductFormPanel() {
        actionListener = (ActionEvent e) -> {
            String action = e.getActionCommand();
            processAction(action);
        };
        initComponents();
        clearForm();
    }

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    private void processAction(String action) {
        if (action != null) {
            switch (action) {
                case "Buscar" -> {
                    search();
                }
                case "Save" -> {
                    save();
                }
                case "Clear" -> {
                    clearForm();
                }
                case "Remove" -> {
                    delete();
                }
                case "Add" -> {
                    product_insert();
                }
            }
            System.out.println("ProductForm> Action: " + action);
        }
    }

    private Product formToProduct() {
        Product product = null;
        try {
            long id = Long.parseLong(jTextField1.getText());
            String code = CodeTextField.getText();
            String description = jTextField3.getText();
            double price = Double.parseDouble(jTextField4.getText());
            int stock = Integer.parseInt(jTextField5.getText());
            product = new Product(id, code, description, price, stock);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid data", "Validation error", JOptionPane.ERROR_MESSAGE);
        }
        return product;
    }

    private void productToForm(Product product) {
        jTextField1.setText(String.valueOf(product.getId()));
        CodeTextField.setText(product.getCode());
        jTextField3.setText(product.getDescription());
        jTextField4.setText(String.valueOf(product.getPrice()));
        jTextField5.setText(String.valueOf(product.getStock()));
    }

    public void clearForm() {
        productToForm(new Product(0, "", "", 0.0, 0));
    }

    public void save() {
        Product p = formToProduct();
        if (p != null) {
            int res = Model.productService.modify(product, p);
            if (res == 1) {
                alert("Successfully saved");
                product = p;
            } else {
                alert("Not modified");
            }
            product = p;
        }
    }

    public void delete() {
        Product p = formToProduct();
        if (p != null) {
            int res = Model.productService.remove(p);
            if (res == 1) {
                alert("Successfully deleted");
                product = p;
            } else {
                alert("Not deleted");
            }
            product = p;
        }
    }

    public void product_insert() {
        Product p = formToProduct();
        if (p != null) {
            int res = Model.productService.add(p);
            if (res == 1) {
                alert("Successfully inserted");
                product = p;
            } else {
                alert("Not inserted");
            }
            product = p;
        }
    }

    public void search() {
        String code = CodeTextField.getText();
        Product p = Model.productService.findByCode(new Product(0, code));
        if (p != null) {
            productToForm(p);
            product = p;
        } else {
            alert("Not found");
        }
    }

    public void alert(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Result", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        IdLb = new javax.swing.JLabel();
        CodeLb = new javax.swing.JLabel();
        DescriptionLb = new javax.swing.JLabel();
        AddBt = new javax.swing.JButton();
        SaveBt = new javax.swing.JButton();
        RemoveBt = new javax.swing.JButton();
        clearBt = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        CodeTextField = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product Form");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        IdLb.setText("Id");

        CodeLb.setText("Code");

        DescriptionLb.setText("Descripcion");

        AddBt.setText("Add");
        AddBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processAction(evt);
            }
        });

        SaveBt.setText("Save");
        SaveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processAction(evt);
            }
        });

        RemoveBt.setText("Remove");
        RemoveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processAction(evt);
            }
        });

        clearBt.setText("Clear");
        clearBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processAction(evt);
            }
        });

        jTextField1.setText("tfId");

        CodeTextField.setText("tfCode");

        jTextField3.setText("tfDescription");

        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processAction(evt);
            }
        });

        jLabel5.setText("Precio");

        jTextField4.setText("tfPrice");

        jLabel6.setText("Stock");

        jTextField5.setText("tfStock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DescriptionLb)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(CodeLb)
                                .addGap(18, 18, 18)
                                .addComponent(CodeTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(IdLb)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddBt)
                        .addGap(18, 18, 18)
                        .addComponent(SaveBt)
                        .addGap(18, 18, 18)
                        .addComponent(RemoveBt)
                        .addGap(18, 18, 18)
                        .addComponent(clearBt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLb)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeLb)
                    .addComponent(CodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescriptionLb)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBt)
                    .addComponent(SaveBt)
                    .addComponent(RemoveBt)
                    .addComponent(clearBt))
                .addGap(33, 33, 33))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void processAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processAction
        processAction(evt.getActionCommand());
    }//GEN-LAST:event_processAction


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBt;
    private javax.swing.JLabel CodeLb;
    private javax.swing.JTextField CodeTextField;
    private javax.swing.JLabel DescriptionLb;
    private javax.swing.JLabel IdLb;
    private javax.swing.JButton RemoveBt;
    private javax.swing.JButton SaveBt;
    private javax.swing.JButton clearBt;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
