/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cat.proven.guiprod.view;

import cat.proven.guiprod.model.Model;
import cat.proven.guiprod.model.Product;
import java.util.List;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author dax
 */
public class ProductListPanel extends javax.swing.JPanel {

    
    private Model model;
    private Product product;
    private final List<Product> products;
    private final String[] columnNames = {
        "Id",
        "Code",
        "Description",
        "Price",
        "Stock"
    };
    
    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    
    /**
     * Creates new form ProductListPanel
     */
    public ProductListPanel(Model modelo) {
        this.model = model;
        products = Model.productService.findAll();
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new ProductTableModel());
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private static class ProductTableModel extends AbstractTableModel {

        private final List<Product> products;

        private final String[] columnNames = {
            "Id",
            "Code",
            "Description",
            "Price",
            "Stock"
        };

        public ProductTableModel() {
            this.products = Model.productService.findAll();
        }

        private final boolean[] editable = {
            false, true, true, true, true
        };

        @Override
        public int getRowCount() {
            return products.size();
        }

        @Override
        public int getColumnCount() {
            return columnNames.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Product product = products.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return product.getId();
                case 1:
                    return product.getCode();
                case 2:
                    return product.getDescription();
                case 3:
                    return product.getPrice();
                case 4:
                    return product.getStock();
                default:
                    return null;
            }
        }

        @Override
        public boolean isCellEditable(int row, int col) {
            return editable[col];
        }

        @Override
        public String getColumnName(int column) {
            return columnNames[column];
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
            Product product = products.get(rowIndex);
            switch (columnIndex) {
                case 1:
                    product.setCode((String) aValue);
                    break;
                case 2:
                    product.setDescription((String) aValue);
                    break;
                case 3:
                    product.setPrice((double) aValue);
                    break;
                case 4:
                    product.setStock((int) aValue);
                    break;
                default:
                    break;
            }
            fireTableCellUpdated(rowIndex, columnIndex);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
